blank_issues_enabled: false
contact_links:
  - name: Respira for WordPress GitHub Community (Q&A)
    url: https://github.com/webmyc/community/discussions
    about: Ask questions and get help in the Respira for WordPress GitHub Community Discussions.
